#extensions
dot pie: ".py"
dot talon: ".talon"
dot mark down: ".md"
dot shell: ".sh"
dot vim: ".vim"
dot see: ".c"
dot see sharp: ".cs"
dot com: ".com"
dot net: ".net"
dot org: ".org"
dot exe: ".exe"
dot (bin | bend): ".bin"
dot (jason | jay son): ".json"
dot text: ".txt"
dot pdf: ".pdf"
dot doc: ".doc"
dot julia: ".jl"
dot csv: ".csv"
